### PR TITLE
Feat/cc 10

### PR DESCRIPTION
**Pull request by linzhihui2022**

### CODE REVIEW

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/c0a462b26afddbaa890a2fb30abdb46b1bbeba93/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td><b>96.55%</b></td><td><b>50%</b></td><td>100%</td><td>100%</td><td><a href='https://github.com/jan24th/coco-connect/blob/c0a462b26afddbaa890a2fb30abdb46b1bbeba93/src/components/atom/CcButton.tsx#L20'>20</a></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/b330f72e67efadf310c76353ac05f4de42f463b1/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td><b>96.55%</b></td><td><b>50%</b></td><td>100%</td><td>100%</td><td><a href='https://github.com/jan24th/coco-connect/blob/b330f72e67efadf310c76353ac05f4de42f463b1/src/components/atom/CcButton.tsx#L20'>20</a></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>packages/ui</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>60.74%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/Card.tsx'>Card.tsx</a></td><td><b>11.54%</b></td><td>100%</td><td><b>0%</b></td><td><b>12%</b></td><td><a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/Card.tsx#L10-L25'>10&ndash;25</a>, <a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/Card.tsx#L4-L9'>4&ndash;9</a></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/index.tsx'>index.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='6'><b>src/atom/Button</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/Button/Button.tsx'>Button.tsx</a></td><td><b>47.06%</b></td><td>100%</td><td><b>0%</b></td><td><b>48.48%</b></td><td><a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/Button/Button.tsx#L17-L33'>17&ndash;33</a></td></tr><tr><td colspan='6'><b>src/atom/ThemeSwitch</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/ThemeSwitch/ThemeSwitch.tsx'>ThemeSwitch.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='6'><b>src/atom/Toggle</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/Toggle/Toggle.tsx'>Toggle.tsx</a></td><td><b>10.34%</b></td><td>100%</td><td><b>0%</b></td><td><b>10.71%</b></td><td><a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/Toggle/Toggle.tsx#L10-L28'>10&ndash;28</a>, <a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/atom/Toggle/Toggle.tsx#L4-L9'>4&ndash;9</a></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td><b>96.55%</b></td><td><b>50%</b></td><td>100%</td><td>100%</td><td><a href='https://github.com/jan24th/coco-connect/blob/7cb57c6be7331d8099fcd3ccd42c5451aaf872b2/src/components/atom/CcButton.tsx#L20'>20</a></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>packages/ui</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/atom/Button</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/93a1dca3036d79cfc0a3c9e6bdc84a9a4efe0913/src/atom/Button/Button.tsx'>Button.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='6'><b>src/atom/ThemeSwitch</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/93a1dca3036d79cfc0a3c9e6bdc84a9a4efe0913/src/atom/ThemeSwitch/ThemeSwitch.tsx'>ThemeSwitch.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/93a1dca3036d79cfc0a3c9e6bdc84a9a4efe0913/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>packages/ui</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/atom/Button</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/80c6378f7e9eddf53aa7289530a663a48bdf2715/src/atom/Button/Button.tsx'>Button.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='6'><b>src/atom/ThemeSwitch</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/80c6378f7e9eddf53aa7289530a663a48bdf2715/src/atom/ThemeSwitch/ThemeSwitch.tsx'>ThemeSwitch.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/80c6378f7e9eddf53aa7289530a663a48bdf2715/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>apps/coco-live</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/components/atom</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/b807c03d4a957e139f649f9cd76d41a4947ae567/src/components/atom/CcButton.tsx'>CcButton.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Comment by linzhihui2022** [comment]
<h2>packages/ui</h2>Coverage after merging <b>feat/cc-10</b> into <b>main</b> will be<table><tbody><tr><th>100.00%</th></tr></tbody></table>

<details><summary>Coverage Report</summary><table><tbody><tr><th>File</th><th>Stmts</th><th>Branches</th><th>Funcs</th><th>Lines</th><th>Uncovered Lines</th></tr><tr><td colspan='6'><b>src/atom/Button</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/b807c03d4a957e139f649f9cd76d41a4947ae567/src/atom/Button/Button.tsx'>Button.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr><tr><td colspan='6'><b>src/atom/ThemeSwitch</b></td></tr><tr><td>&nbsp; &nbsp;<a href='https://github.com/jan24th/coco-connect/blob/b807c03d4a957e139f649f9cd76d41a4947ae567/src/atom/ThemeSwitch/ThemeSwitch.tsx'>ThemeSwitch.tsx</a></td><td>100%</td><td>100%</td><td>100%</td><td>100%</td><td></td></tr></tbody></table></details>

**Review by Yexuyao123 — APPROVED** [review]

**Pull request merged**
